# -*- coding: utf-8 -*-
"""DAY1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZ2v4evKeUWry-lq-ZwrNKbftHRMEbNf
"""

x=10
print(x)
y=3.14
print(y)
name="john"
pri

print('hello world')
print('mythri')
print('computer science engineering')

print('i am your student')

x=10
print(x)
y=3.14
print(y,name)
name="john"
print(name)
print(name + 'is a teacher')
print(x,y,name)

name=input('enter your name')
a=input('enter a number')
print(name)

a=input("enter your number")
b=input("enter your number")
c=(a+b)
print(c)

"""area of circle"""





a=int(input("enter the number"))
b=int(input("enter the number"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

r=float(input("enter the radius"))
area=3.14*r*r
print(area)

"""temperatur converter"""

celsius=float(input("enter temperature in celsius"))
fahrenheit=(celsius*9/5)+32
print("temperature in fahrenheit:",fahrenheit)